### ISSUE TITLE
Ditch column name requirements in function parameters?

### ISSUE THREAD

**Issue by mhinsch** [mhinsch/rpathsonpaths#11]
Definitely easier for the user and no issue on the C++ side. OTOH it makes it easier to mess up. 
IMO this is mainly a question of which behaviour would be expected by most people.
@thibautjombart what's your opinion on this?

**Comment by thibautjombart** [comment]
I think it doesn't matter to some extent, as if we use `epicontacts` objects as inputs, then the naming thing is going to happen internally in the function passing the `epicontacts` to C++, which we write. I suspect the strongest constraint lies in how you want to design things in the standalone C++ library?

**Comment by mhinsch** [comment]
I have to say, the names requirement gets pretty old on the R side pretty quickly. Let's just drop it.
