### ISSUE TITLE
Naming conventions (camelCase -> underscores)

### ISSUE THREAD

**Issue by mhinsch** [mhinsch/rpathsonpaths#15]
The official guidelines recommend underscore naming for functions and variables (what about types/classes?). While that's my personal preference as well I've used camelCase since I had heard that underscores can cause problems in R. If that's not actually an issue (@thibautjombart?) I will change everything to underscores.

**Comment by thibautjombart** [comment]
Underscores used to be a problem as old versions of S-plus were using it as assignment operator. I don't think this has been a problem for the last .. err.. maybe 10 years, so safe to use ;)
