### ISSUE TITLE
Let PopsNetwork objects survive end of R session

### ISSUE THREAD

**Issue by mhinsch** [mhinsch/rpathsonpaths#18]
If possible PopsNetwork objects should behave like regular R objects, i.e. get saved at session exit and restored at restart. This is a hard to very hard problem, however, and might end up as wontfix.
Stronger version of issue #5.

**Comment by thibautjombart** [comment]
While quite interesting as it pushes the limits of what R tolerates, this looks like a considerable time sink, and something we can work around by not accessing the C++ data representation from R (cf comments on issue https://github.com/mhinsch/rpathsonpaths/issues/5

**Comment by mhinsch** [comment]
too difficult
