### ISSUE TITLE
Specify boost dependency

### ISSUE THREAD

**Issue by thibautjombart** [mhinsch/rpathsonpaths#36]
Not sure what the best way to depend on an external C/C++ library is.
@richfitz may have an idea?

**Comment by richfitz** [comment]
For boost, the best way is to just use the `BH` package.  Don't depend on boost itself unless you know you need something not in `BH`.

Otherwise it's the `SystemRequirements:` fields in DESCRIPTION but that's just a human readable thing

**Comment by thibautjombart** [comment]
Thx!

**Comment by mhinsch** [comment]
Added boost requirements in Readme and Overview, hope that's enough.
